controllers:
  huebridge: 
    hue:
      bridgeIp: "192.168.1.64"
      key: "d-WZEUsdN0IBn69yO1BoFf7UWBr4WDBZcaEM7Cec"
    groups:
    - name: Bedroom Ceiling
      devices: [1, 2]
  computer:
    computer:
      
serverHost: ":8080"
tlsConfig:
  privateKey: C:\Users\ben\Documents\ET_KEYS\key.pem
  publicKey: C:\Users\ben\Documents\ET_KEYS\cert.pem
webViewDir: C:\Users\ben\Documents\Go\src\github.com\ben-turner\explosive-transistor2\webview\